### ISSUE TITLE
Search Features

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#1815]
I'd like to add the ability to use the [SoftLayer_Search](https://sldn.softlayer.com/reference/services/SoftLayer_Search/) service basically all over the place, or at least for the Datatypes supported by it.

Each of these should have their own issue opened to track their completion. This issue will stand in for the whole feature.

## TODO

- [x]  Add a Search manager base class. 
These functions should be pretty basic, taking in as parameters anything the API method would take in, and just returning the result.
  - [x]  function for [getObjectTypes](https://sldn.softlayer.com/reference/services/SoftLayer_Search/getObjectTypes/)
  - [x] function for [search](https://sldn.softlayer.com/reference/services/SoftLayer_Search/search/)
  - [x] function for [advancedSearch](https://sldn.softlayer.com/reference/services/SoftLayer_Search/advancedSearch/)
- [x] Add a search CLI function `slcli search "query"` 
  - [x]  Help message should have the url for the  search API docs and the [SLDN search article](https://sldn.softlayer.com/article/softlayer_search/) along with a few examples
  - [x]  Option for `--advanced` which will just send the query to the advancedSearch api
  - [x] Option for `--types` will print out the result of getObjectTypes
- [x]   A search option for `slcli vs list --search "query"` which should list all vsis that match that query. Might need a special search manager function for this.
- [x] A search option for `slcli vs detail`. My thought is that if the input isn't a number, or we get a 404 error, try a search query just in case. If there is more than 1 result, should print them all out.
- [x] A search option for `slcli hw list --search "query"`
- [x] A search option for `slcli hw detail`. (same as vs basically)

For now this feature will only cover this list of things, but there are other search objects we can add as well.

- SoftLayer_Ticket
- SoftLayer_Network_Vlan_Firewall
- SoftLayer_Network_Vlan
- SoftLayer_Network_Subnet_IpAddress
- SoftLayer_Network_Application_Delivery_Controller
- SoftLayer_Virtual_DedicatedHost
- SoftLayer_Event_Log
